config/routes.rb
Rails.application.routes.draw do
  get 'maps/map'

  resources :events

  root 'events#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @event = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
  end

  def edit
    @event = Event.find(params[:id])
  end
  def create
    @event = Event.new(event_params)

    @event.save
    redirect_to @event
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to events_path
  end

  private
    def event_params
      params.require(:event).permit(:name, :category, :place, :price, :date, :time, :description, :submits)
    end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def map
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/edit.html.erb
<h1>Editing article</h1>

<%= form_for :event, url: event_path(@event), method: :patch do |f| %>
<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :category %><br>
  <%= f.text_field :category %>
</p>
<p>
  <%= f.label :place %><br>
  <%= f.text_field :place %>
</p>
<p>
  <%= f.label :price %><br>
  <%= f.number_field :price %>
</p>
<p>
  <%= f.label :date %><br>
  <%= f.date_field :date %>
</p>
<p>
  <%= f.label :time %><br>
  <%= f.time_field :time %>
</p>
<p>
  <%= f.label :submits %><br>
  <%= f.number_field :submits %>
<p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', event_path %>

app/views/events/index.html.erb
<script src="http://www.localworksupporter.com/jquery213min.js"></script>
 <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<div class="nav">
  <img class="brand" src="http://www.localworksupporter.com/wbrand.png" /><img class="typo" src="http://www.localworksupporter.com/TYPE.png" />
  <button id="btnFilter" type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">Filter<i class="fa fa-bars"></i></button>
  <div class="inner">
    <p class="space">
      <a href="http://localhost:3000/maps/map">
        <img class="globe" src="http://www.localworksupporter.com/globe.png" width="87"/></a></p>
  </div>
  <a href="#" class="button gray login" onclick="loginOverlay()">LOGIN</a></div>
  <div id="lgOverlay" style="visibility: hidden;">
  <div id="dialog" title="Basic dialog">
  <p>
  <div class="loginBox">
          <h1>Login</h1>
        <form method="post">
            <input type="text" name="u" placeholder="Username" required="required" />
            <input type="password" name="p" placeholder="Password" required="required" />
          <button type="submit" class="btn btn-primary btn-block btn-large">Sign in</button>
            </form>
  </div>
  </p>
  </div>
 </div>
<div class="wrapper">
<div class="timeline"></div>
<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Place</th>
    <th>Price</th>
    <th>Date</th>
    <th>Submits</th>
  </tr>

  <% @event.each do |event| %>
    <tr>
      <td class="name"><%= event.name %></td>
      <td class="category"><%= event.category %></td>
      <td class="place"><%= event.place %></td>
      <td class="price"><%= event.price %></td>
      <td class="date"><%= event.date %></td>
      <td class="submits"><%= event.submits %></td>
      <td><%= link_to 'Show', event_path(event) %></td>
      <td><%= link_to 'Edit', edit_event_path(event) %></td>
      <td><%= link_to 'Destroy', event_path(event),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'New Event', new_event_path %>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">

        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

      </div>

      <div class="modal-body">
        <div><h5>Category</h5>
     <input type="checkbox">All categories
     <input type="checkbox">Sport
     <input type="checkbox">Music
     <input type="checkbox">Education
     <input type="checkbox">Science/Tech
     <input type="checkbox">Spiritual
     <input type="checkbox">Other
        </div>
                <div><h5>Date</h5>
    <input type="checkbox">Today
  <input type="checkbox">Tomorrow
    <input type="checkbox">This Week
    <input type="checkbox">Next Weekend
    <input type="checkbox">This Month
        </div>

         <div><h5>Price</h5>
     <input type="checkbox">Free
     <input type="checkbox">1-100
     <input type="checkbox">101-250
     <input type="checkbox">251-500
     <input type="checkbox">501-1000
     <input type="checkbox">1000+
        </div>

         <div><h5>Zip Code</h5>
  <input type="text" name="zipcode">
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Search</button>
      </div>
    </div>
</div>


 </div>

<script>
$(document).ready(function () {


  var stickyNavTop = $(".nav").offset().top;

  var stickyNav = function(){
  var scrollTop = $(window).scrollTop();

if (scrollTop > stickyNavTop) {
  $(".nav").addClass("sticky");
  } else {
  $(".nav").removeClass("sticky");
  }
};

stickyNav();

 $(window).scroll(function() {
   stickyNav();
 });
});

function loginOverlay() {
  var enterCode = document.getElementById("lgOverlay");
  enterCode.style.visibility = (enterCode.style.visibility == "visible") ? "hidden" : "visible";
}

var anchor = document.getElementsByTagName('a');
anchor[5].className += " " + "btn";
anchor[5].className += " " + "btn-primary";
anchor[5].className += " " + "btn-block";
anchor[5].className += " " + "btn-large";

 </script>

app/views/events/new.html.erb
<h1>Add an event</h1>
<%= form_for :event, url: events_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>
  <p>
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </p>
  <p>
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </p>
  <p>
    <%= f.label :time %><br>
    <%= f.time_field :time %>
  </p>
  <p>
    <%= f.label :submits %><br>
    <%= f.number_field :submits %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/events/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @event.category %>
</p>

<p>
  <strong>Place:</strong>
  <%= @event.place %>
</p>

<p>
  <strong>Price:</strong>
  <%= @event.price %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @event.time %>
</p>

<p>
  <strong>Submits:</strong>
  <%= @event.submits %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>


<%= link_to 'Show Events', controller: 'events' %>|
<%= link_to 'Edit', edit_event_path(@event) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weventus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/maps/map.html.erb
<!DOCTYPE html>
<html>
    <head>
    <script src="http://www.localworksupporter.com/jquery1112min.js"></script>
<script src="http://www.localworksupporter.com/jquery213min.js"></script>
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
        <style type="text/css">
              html { height: 100% }
              body { height: 100%; margin: 5; }
              #mapDiv { width: 800px; height: 500px; }
        </style>
        <!-- Include Google Maps JS API -->
        <script type="text/javascript"
          src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBR48eWLpcfyXoBH5YbJvBRfdvpRfDymxo&libraries=drawing,places&sensor=false">
        </script>

  <!-- Map creation is here -->
        <script type="text/javascript">
              //Defining map as a global variable to access from other functions
              var map;
        //define a global circles array variable, to push and pop the circle overlays
        var circles;
        //define a global markers array variable, to push and pop the circle overlays
        var markers;
        //define global marker popup variable
        var popup;

              function initMap() {
                    //initialize circles array
          circles = new Array();

          //initialize markers array
          markers = new Array();

          //initialize info popup window
          popup = new google.maps.InfoWindow();

          //Enabling new cartography and themes
                    google.maps.visualRefresh = true;

                    //Setting starting options of map
                    var mapOptions = {
                          center: new google.maps.LatLng(30.441878,-84.298489),
                          zoom: 10,
                          mapTypeId: google.maps.MapTypeId.ROADMAP
                    };

                    //Getting map DOM element
                    var mapElement = document.getElementById("mapDiv");

                    //Creating a map with DOM element which is just obtained
                    map = new google.maps.Map(mapElement, mapOptions);

          //creating drawingManager
          var drawingManager = new google.maps.drawing.DrawingManager({
            //initial drawing tool to be enabled
            drawingMode:google.maps.drawing.OverlayType.CIRCLE,
            //enable the drawingControl to be seen in the UI
            drawingControl:true,
            //select which drawing modes to be seen in the drawingControl and position them
            drawingControlOptions: {
              //select a position in the UI
              position: google.maps.ControlPosition.BOTTOM_CENTER,
              //selected drawing modes to be seen in the control
              drawingModes: [
                google.maps.drawing.OverlayType.CIRCLE
              ]
            }
          });

          //enable drawing functionality
          drawingManager.setMap(map);

          //add event listener for completion of your circle
          google.maps.event.addListener(drawingManager, 'circlecomplete', function(circle) {
            //exit the circle drawing mode
            drawingManager.setDrawingMode(null);

            //add the latest drawn circle to the circles array
            circles.push(circle);
            //reverse the circles array, to pop the previous drawn circle
            circles.reverse();


            while(circles[1])
            {
              circles.pop().setMap(null);
            }


            //clear all previously drawn markers
            while(markers[0])
            {
              markers.pop().setMap(null);
            }

            var nearbyPlacesRequest = {
              location: circle.getCenter(),
              radius: circle.radius,
              keyword: 'night club'
            };

            //get the handle for PlacesService service
            var placesService = new google.maps.places.PlacesService(map);
            //send the request with a callback
            placesService.nearbySearch(nearbyPlacesRequest, resultsCallback);
          });
        }

        //the callback function that returns the places
        function resultsCallback(results, status) {
          //checking the service status
          if (status == google.maps.places.PlacesServiceStatus.OK) {
            //getting the results array containing the places
            for (var i = 0, l=results.length; i < l; i++) {
              //put a marker in the map and attach a infowindow to display its details
              pinpointResult(results[i]);
            }
          }
        }

        //put a marker in the map and attach a infowindow to display its details
        function pinpointResult(result) {
          //marker stuff
          var marker = new google.maps.Marker({
            map: map,
            position: result.geometry.location
          });

          //infowindow stuff
          google.maps.event.addListener(marker, 'click', function() {
            //debugger;
            var popupContent = '<b>Name: </b> ' + result.name + '<br/>' + '<b>Vicinity: </b>' + result.vicinity + '<br/><b>Rating: </b>' + result.rating;
            popup.setContent(popupContent);
            popup.open(map, this);
          });

          //add the latest drawn marker to the markers array
          markers.push(marker);
        }

        </script>
    </head>

  <div class="nav"><img class="brand" src="http://www.localworksupporter.com/wbrand.png" /><img class="typo" src="http://www.localworksupporter.com/TYPE.png" /><button id="btnFilter" type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">Filter<i class="fa fa-bars"></i></button><div class="inner2">
    <p class="space"><a href="/events"><img class="listButt" src="http://www.localworksupporter.com/listicon.png" width="87"/></a></p>
  </div><a href="#" class="button gray login" onclick="loginOverlay()">LOGIN</a></div>
<div id="mapDiv"></div>

  <div id="lgOverlay" style="visibility: hidden;">

    <div id="dialog" title="Basic dialog">
  <p>
  <div class="loginBox">
          <h1>Login</h1>
        <form method="post">
            <input type="text" name="u" placeholder="Username" required="required" />
            <input type="password" name="p" placeholder="Password" required="required" />
          <button type="submit" class="btn btn-primary btn-block btn-large">Sign in</button>
            </form>
  </div>
  </p>
   </div>

 </div>




  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">

        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

      </div>

      <div class="modal-body">
        <div><h5>Category</h5>
     <input type="checkbox">All categories
     <input type="checkbox">Sport
     <input type="checkbox">Music
     <input type="checkbox">Education
     <input type="checkbox">Science/Tech
     <input type="checkbox">Spiritual
     <input type="checkbox">Other
        </div>
                <div><h5>Date</h5>
    <input type="checkbox">Today
  <input type="checkbox">Tomorrow
    <input type="checkbox">This Week
    <input type="checkbox">Next Weekend
    <input type="checkbox">This Month
        </div>

         <div><h5>Price</h5>
     <input type="checkbox">Free
     <input type="checkbox">1-100
     <input type="checkbox">101-250
     <input type="checkbox">251-500
     <input type="checkbox">501-1000
     <input type="checkbox">1000+
        </div>

         <div><h5>Zip Code</h5>
  <input type="text" name="zipcode">
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Search</button>
      </div>
    </div>
</div>


 </div>
    <body onload="initMap()">
        <b>WEventus Map View </b><br/>
        <div id="mapDiv"/>
        <script>
        $(document).ready(function () {


  var stickyNavTop = $(".nav").offset().top;

  var stickyNav = function(){
  var scrollTop = $(window).scrollTop();

if (scrollTop > stickyNavTop) {
  $(".nav").addClass("sticky");
  } else {
  $(".nav").removeClass("sticky");
  }
};

stickyNav();

 $(window).scroll(function() {
   stickyNav();
 });
});

        function loginOverlay() {
  var enterCode = document.getElementById("lgOverlay");
  enterCode.style.visibility = (enterCode.style.visibility == "visible") ? "hidden" : "visible";
}
        </script>
    </body>
</html>

app/views/welcome/index.html.erb
<h1>Weventus</h1>
<%= link_to 'Events', controller: 'events' %>